version: '3'

services:
  db:
    image: dannygoldstein/zuds-db:latest
    ports:
       - 8271:5432

  zuds:
    image: dannygoldstein/zuds-demo:latest
    ports:
       - 8174:8888
    links:
       - db
    volumes:
       - .:/home/zuds/demo



